source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'oj'
gem 'rabl'
gem 'slim'
gem 'puma'
gem 'bson_ext'
gem 'mongoid'
gem 'bcrypt-ruby', require: 'bcrypt'
